### ISSUE TITLE
CIXReader doesn't handle an empty .ini file well.

### ISSUE THREAD

**Issue by simsclub** [cixonline/cixreader#4]
If the .ini file is empty, CIXReader reports "Cannot create log file. Object reference not set to an instance of an
object". 

We could handle this better by reporting a more helpful error, and by offering to re-create the empty .ini file.

**Comment by ghost** [comment]
The error is about CIXReader not being able to find the `[Main]` section in the `.ini`.

Seeing as we will *create* a file with a correct `[Main]` section if the `.ini` doesn't exist, I think this doesn't really need to be something the user is warned about, simply just create the section automatically if it doesn't exist, just like we create the file automatically.

Simple fix, in any case.
